# Environment where the service is running
env: local

# Listening port of the serivce
http:
  port: "8081"

# The project artifact and version data 
project:
  artifact: "${project.artifactId}"
  version: "${project.version}"

# The RAML API and autodiscovery
api:  
  group: "${restconnector.api.spec.group}"
  artifact: "${restconnector.api.spec.artifact}"
  version: "${restconnector.api.spec.version}"
  spec: "resource::${api.group}:${api.artifact}:${api.version}:raml:zip:api.raml"
  id: "0"

# Open Telemetry configuration
otel:
  servicename: "${project.name}:${project.version}"

# Service messages
messages:
  customer-doesnt-exist-relations: "Customer does not exist or has relations with other resources"
  customer-exists: "Customer already exists"
  customer-error: "There was a problem while trying to create the Customer"
  customer-deleted: "Customer deleted successfully"
  
# Components to configure:
# - Salesforce connector
# - OpenTelemtry connector
# - logzio (logging platform)
# - Mulesoft Gatekeeper
