name: Release
 
on:
  release:
    type: created

jobs: 
  Mulesoft:
    uses: jpontdia/common-devops/.github/workflows/release.yml@main
    with:
      keyvault-key: jpworks-keyvault
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
