name: Release
 
on:
  release:
    types: [created]
    
jobs: 
  Mulesoft:
    uses: jpontdia/common-devops/.github/workflows/mulesoft-release.yml@main
    with:
      keyvault-key: jpworks-keyvault
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
