name: Release
 
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write
      
jobs: 
  Mulesoft:
    uses: jpontdia/common-devops/.github/workflows/mulesoft-release.yml@main
    with:
      keyvault-key: jpworks-keyvault
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
